# Verwende das aktuelle Minima-Theme direkt per Remote Theme
remote_theme: jekyll/minima
# theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag   # optional, für schöne Meta-Daten (Feed deaktiviert)
  - jekyll-toc

title: DND Campaign Assistant
author: René
description: "DND Campaign Helper Page."

# Minima-Einstellungen
minima:
  skin: dark         # dark, light, auto, solarized
  date_format: "%d.%m.%Y"
  hide_site_feed_link: true
  
# Nur diese Seiten sollen in der Navigation erscheinen
#header_pages:
  nav_pages:
    - homebrew.md
    - shops.md
#   - projects.md

#   Set to `true` to show excerpts on the homepage.
  show_excerpts: true
