# Verwende das aktuelle Minima-Theme direkt per Remote Theme
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag   # optional, für schöne Meta-Daten (Feed deaktiviert)
  - jekyll-feed

title: DND Campaign Assistant
author: René
description: "DND Campaign Helper Page."

# Minima-Einstellungen
minima:
  skin: dark         # dark, light, auto, solarized
  date_format: "%d.%m.%Y"

# Nur diese Seiten sollen in der Navigation erscheinen
#header_pages:
#  - about.md
#  - projects.md
nav_pages:
  - homebrew.md

#   Set to `true` to show excerpts on the homepage.
show_excerpts: true

# RSS-Feed-Link im Footer deaktivieren
hide_site_feed_link: true
